const movieDatabase = {
  ironman1: {
    title: "Iron Man",
    year: "2008",
    poster: "https://upload.wikimedia.org/wikipedia/en/0/00/Iron_Man_poster.jpg",
    genre: "Action, Sci-Fi",
    rating: "7.9",
    overview: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    cast: "Robert Downey Jr., Gwyneth Paltrow, Jeff Bridges, Terrence Howard",
    trailerId: "8ugaeA-nMTc",
    downloadUrl: "#"
  },
  ironman2: {
    title: "Iron Man 2",
    year: "2010",
    poster: "https://upload.wikimedia.org/wikipedia/en/e/ed/Iron_Man_2_poster.jpg",
    genre: "Action, Sci-Fi, Adventure",
    rating: "6.9",
    overview: "With the world now aware of his identity, Tony Stark must contend with declining health and a vengeful madman with ties to his father's legacy.",
    cast: "Robert Downey Jr., Mickey Rourke, Gwyneth Paltrow, Don Cheadle",
    trailerId: "wKtcmiifycU",
    downloadUrl: "#"
  },
  ironman3: {
    title: "Iron Man 3",
    year: "2013",
    poster: "https://upload.wikimedia.org/wikipedia/en/1/19/Iron_Man_3_poster.jpg",
    genre: "Action, Sci-Fi, Adventure",
    rating: "7.1",
    overview: "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
    cast: "Robert Downey Jr., Guy Pearce, Gwyneth Paltrow, Ben Kingsley",
    trailerId: "YLorLVa95Xo",
    downloadUrl: "#"
  },
  captainamerica1: {
    title: "Captain America: The First Avenger",
    year: "2011",
    poster: "https://upload.wikimedia.org/wikipedia/en/3/37/Captain_America_The_First_Avenger_poster.jpg",
    genre: "Action, Adventure, Sci-Fi",
    rating: "6.9",
    overview: "Steve Rogers transforms into Captain America after taking a Super-Soldier serum to stop the Red Skull.",
    cast: "Chris Evans, Hugo Weaving, Samuel L. Jackson, Hayley Atwell",
    trailerId: "JerVrbLldXw",
    downloadUrl: "#"
  },
  captainamerica2: {
    title: "Captain America: The Winter Soldier",
    year: "2014",
    poster: "https://upload.wikimedia.org/wikipedia/en/e/e8/Captain_America_The_Winter_Soldier.jpg",
    genre: "Action, Sci-Fi, Thriller",
    rating: "7.8",
    overview: "Steve Rogers teams up with Natasha Romanoff to battle a powerful assassin known as the Winter Soldier.",
    cast: "Chris Evans, Scarlett Johansson, Sebastian Stan, Anthony Mackie",
    trailerId: "7SlILk2WMTI",
    downloadUrl: "#"
  },
  captainamerica3: {
    title: "Captain America: Civil War",
    year: "2016",
    poster: "https://upload.wikimedia.org/wikipedia/en/5/53/Captain_America_Civil_War_poster.jpg",
    genre: "Action, Sci-Fi, Adventure",
    rating: "7.8",
    overview: "Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.",
    cast: "Chris Evans, Robert Downey Jr., Scarlett Johansson, Sebastian Stan",
    trailerId: "dKrVegVI0Us",
    downloadUrl: "#"
  },
  thor1: {
    title: "Thor",
    year: "2011",
    poster: "https://upload.wikimedia.org/wikipedia/en/f/fc/Thor_poster.jpg",
    genre: "Action, Fantasy, Sci-Fi",
    rating: "7.0",
    overview: "The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard.",
    cast: "Chris Hemsworth, Anthony Hopkins, Natalie Portman, Tom Hiddleston",
    trailerId: "JOddp-nlNvQ",
    downloadUrl: "#"
  },
  thor2: {
    title: "Thor: The Dark World",
    year: "2013",
    poster: "https://upload.wikimedia.org/wikipedia/en/7/7f/Thor_The_Dark_World_poster.jpg",
    genre: "Action, Fantasy, Sci-Fi",
    rating: "6.8",
    overview: "When the Dark Elves attempt to plunge the universe into darkness, Thor must embark on a perilous personal journey.",
    cast: "Chris Hemsworth, Natalie Portman, Tom Hiddleston, Christopher Eccleston",
    trailerId: "npvJ9FTgZbM",
    downloadUrl: "#"
  },
  thor3: {
    title: "Thor: Ragnarok",
    year: "2017",
    poster: "https://upload.wikimedia.org/wikipedia/en/7/7d/Thor_Ragnarok_poster.jpg",
    genre: "Action, Adventure, Comedy",
    rating: "7.9",
    overview: "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök.",
    cast: "Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Mark Ruffalo",
    trailerId: "ue80QwXMRHg",
    downloadUrl: "#"
  },
  thor4: {
    title: "Thor: Love and Thunder",
    year: "2022",
    poster: "https://upload.wikimedia.org/wikipedia/en/8/88/Thor_Love_and_Thunder_poster.jpeg",
    genre: "Action, Adventure, Comedy",
    rating: "6.2",
    overview: "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher.",
    cast: "Chris Hemsworth, Christian Bale, Natalie Portman, Tessa Thompson",
    trailerId: "Go8nTmfrQd8",
    downloadUrl: "#"
  },
  avengers1: {
    title: "The Avengers",
    year: "2012",
    poster: "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg",
    genre: "Action, Sci-Fi",
    rating: "8.0",
    overview: "Earth's mightiest heroes must come together and learn to fight as a team to stop Loki and his alien army.",
    cast: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson",
    trailerId: "eOrNdBpGMv8",
    downloadUrl: "#"
  },
  avengers2: {
    title: "Avengers: Age of Ultron",
    year: "2015",
    poster: "https://upload.wikimedia.org/wikipedia/en/f/ff/Avengers_Age_of_Ultron_poster.jpg",
    genre: "Action, Sci-Fi, Adventure",
    rating: "7.3",
    overview: "When Tony Stark and Bruce Banner try to jump-start a peace program, things go wrong and the Avengers must stop Ultron.",
    cast: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, James Spader",
    trailerId: "tmeOjFno6Do",
    downloadUrl: "#"
  },
  avengers3: {
    title: "Avengers: Infinity War",
    year: "2018",
    poster: "https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg",
    genre: "Action, Adventure, Sci-Fi",
    rating: "8.4",
    overview: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos.",
    cast: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans, Josh Brolin",
    trailerId: "6ZfuNTqbHE8",
    downloadUrl: "#"
  },
  avengers4: {
    title: "Avengers: Endgame",
    year: "2019",
    poster: "https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg",
    genre: "Action, Adventure, Drama",
    rating: "8.4",
    overview: "After the devastating events of Infinity War, the universe is in ruins. The remaining Avengers assemble to restore balance.",
    cast: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson",
    trailerId: "TcMBFSGVi1c",
    downloadUrl: "#"
  },
  guardians1: {
    title: "Guardians of the Galaxy",
    year: "2014",
    poster: "https://upload.wikimedia.org/wikipedia/en/b/b5/Guardians_of_the_Galaxy_poster.jpg",
    genre: "Action, Adventure, Comedy",
    rating: "8.0",
    overview: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    cast: "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel, Bradley Cooper",
    trailerId: "d96cjJhvlMA",
    downloadUrl: "#"
  },
  guardians2: {
    title: "Guardians of the Galaxy Vol. 2",
    year: "2017",
    poster: "https://upload.wikimedia.org/wikipedia/en/a/ab/Guardians_of_the_Galaxy_Vol_2_poster.jpg",
    genre: "Action, Adventure, Comedy",
    rating: "7.6",
    overview: "The Guardians struggle to keep together as a team while dealing with personal family issues, notably Star-Lord's father.",
    cast: "Chris Pratt, Zoe Saldana, Dave Bautista, Kurt Russell",
    trailerId: "2Xy3n5l7PjQ",
    downloadUrl: "#"
  },
  guardians3: {
    title: "Guardians of the Galaxy Vol. 3",
    year: "2023",
    poster: "https://upload.wikimedia.org/wikipedia/en/7/74/Guardians_of_the_Galaxy_Vol._3_poster.jpg",
    genre: "Action, Adventure, Comedy",
    rating: "7.9",
    overview: "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and protect one of their own.",
    cast: "Chris Pratt, Chukwudi Iwuji, Bradley Cooper, Karen Gillan",
    trailerId: "u3V5KDHRQvk",
    downloadUrl: "#"
  },
  blackpanther1: {
    title: "Black Panther",
    year: "2018",
    poster: "https://upload.wikimedia.org/wikipedia/en/d/d6/Black_Panther_film_poster.jpg",
    genre: "Action, Sci-Fi",
    rating: "7.3",
    overview: "T'Challa, heir to the hidden kingdom of Wakanda, must step forward to lead his people into a new future.",
    cast: "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Danai Gurira",
    trailerId: "xjDjIWPwcPU",
    downloadUrl: "#"
  },
  doctorstrange1: {
    title: "Doctor Strange",
    year: "2016",
    poster: "https://upload.wikimedia.org/wikipedia/en/a/a1/Doctor_Strange_poster.jpg",
    genre: "Action, Fantasy, Sci-Fi",
    rating: "7.5",
    overview: "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
    cast: "Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams, Tilda Swinton",
    trailerId: "HSzx-zryEgM",
    downloadUrl: "#"
  },
  doctorstrange2: {
    title: "Doctor Strange in the Multiverse of Madness",
    year: "2022",
    poster: "https://upload.wikimedia.org/wikipedia/en/1/17/Doctor_Strange_in_the_Multiverse_of_Madness_poster.jpg",
    genre: "Action, Fantasy, Horror",
    rating: "6.9",
    overview: "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses.",
    cast: "Benedict Cumberbatch, Elizabeth Olsen, Xochitl Gomez, Benedict Wong",
    trailerId: "aWzlQ2N6uoM",
    downloadUrl: "#"
  },
  spidermanhomecoming: {
    title: "Spider-Man: Homecoming",
    year: "2017",
    poster: "https://upload.wikimedia.org/wikipedia/en/f/f9/Spider-Man_Homecoming_poster.jpg",
    genre: "Action, Adventure, Sci-Fi",
    rating: "7.4",
    overview: "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man.",
    cast: "Tom Holland, Michael Keaton, Robert Downey Jr., Zendaya",
    trailerId: "n9DwoQ7HWvI",
    downloadUrl: "#"
  },
  spidermanfarfromhome: {
    title: "Spider-Man: Far From Home",
    year: "2019",
    poster: "https://upload.wikimedia.org/wikipedia/en/b/bd/Spider-Man_Far_From_Home_poster.jpg",
    genre: "Action, Adventure, Sci-Fi",
    rating: "7.4",
    overview: "Following the events of Endgame, Spider-Man must step up to take on new threats in a world that has changed forever.",
    cast: "Tom Holland, Samuel L. Jackson, Jake Gyllenhaal, Zendaya",
    trailerId: "Nt9L1jCKGnE",
    downloadUrl: "#"
  },
  spidermannowayhome: {
    title: "Spider-Man: No Way Home",
    year: "2021",
    poster: "https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg",
    genre: "Action, Adventure, Fantasy",
    rating: "8.2",
    overview: "With Spider-Man's identity revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes appear.",
    cast: "Tom Holland, Zendaya, Benedict Cumberbatch, Willem Dafoe",
    trailerId: "JfVOs4VSpmA",
    downloadUrl: "#"
  },
  batmanbegins: {
    title: "Batman Begins",
    year: "2005",
    poster: "https://upload.wikimedia.org/wikipedia/en/a/af/Batman_Begins_Poster.jpg",
    genre: "Action, Crime, Drama",
    rating: "8.2",
    overview: "After training with his mentor, Bruce Wayne begins his fight to free crime-ridden Gotham City from corruption.",
    cast: "Christian Bale, Michael Caine, Liam Neeson, Katie Holmes, Gary Oldman",
    trailerId: "neY2xVmOfUM",
    downloadUrl: "#"
  },
  thedarkknight: {
    title: "The Dark Knight",
    year: "2008",
    poster: "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg",
    genre: "Action, Crime, Drama",
    rating: "9.0",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests.",
    cast: "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine, Gary Oldman",
    trailerId: "EXeTwQWrcwY",
    downloadUrl: "#"
  },
  thedarkknightrises: {
    title: "The Dark Knight Rises",
    year: "2012",
    poster: "https://upload.wikimedia.org/wikipedia/en/8/83/Dark_knight_rises_poster.jpg",
    genre: "Action, Drama, Thriller",
    rating: "8.4",
    overview: "Eight years after the Joker's reign of anarchy, Batman is forced from his exile by the brutal guerrilla terrorist Bane.",
    cast: "Christian Bale, Tom Hardy, Anne Hathaway, Gary Oldman, Joseph Gordon-Levitt",
    trailerId: "g8evyE9TuYg",
    downloadUrl: "#"
  },
  manofsteel: {
    title: "Man of Steel",
    year: "2013",
    poster: "https://upload.wikimedia.org/wikipedia/en/8/85/ManofSteelFinalPoster.jpg",
    genre: "Action, Adventure, Sci-Fi",
    rating: "7.1",
    overview: "An alien child is evacuated from his dying world and sent to Earth, where he must become the hero known as Superman.",
    cast: "Henry Cavill, Amy Adams, Michael Shannon, Kevin Costner",
    trailerId: "T6DJcgm3wNY",
    downloadUrl: "#"
  },
  batmanvsuperman: {
    title: "Batman v Superman: Dawn of Justice",
    year: "2016",
    poster: "https://upload.wikimedia.org/wikipedia/en/2/20/Batman_v_Superman_Dawn_of_Justice_poster.jpg",
    genre: "Action, Adventure, Sci-Fi",
    rating: "6.5",
    overview: "Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of hero it needs.",
    cast: "Ben Affleck, Henry Cavill, Amy Adams, Jesse Eisenberg, Gal Gadot",
    trailerId: "0WWzgGyAH6Y",
    downloadUrl: "#"
  },
  wonderwoman1: {
    title: "Wonder Woman",
    year: "2017",
    poster: "https://upload.wikimedia.org/wikipedia/en/e/ed/Wonder_Woman_%282017_film%29.jpg",
    genre: "Action, Adventure, Fantasy",
    rating: "7.4",
    overview: "When a pilot crashes and tells of conflict in the outside world, Diana leaves home to fight in a war to end all wars.",
    cast: "Gal Gadot, Chris Pine, Robin Wright, Danny Huston",
    trailerId: "1Q8fG0TtVAY",
    downloadUrl: "#"
  },
  justiceleague: {
    title: "Zack Snyder's Justice League",
    year: "2021",
    poster: "https://upload.wikimedia.org/wikipedia/en/3/31/Justice_League_film_poster.jpg",
    genre: "Action, Adventure, Fantasy",
    rating: "7.9",
    overview: "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince to recruit a team of metahumans.",
    cast: "Ben Affleck, Henry Cavill, Gal Gadot, Jason Momoa, Ray Fisher, Ezra Miller",
    trailerId: "vM-Bja2Gy04",
    downloadUrl: "#"
  },
  aquaman1: {
    title: "Aquaman",
    year: "2018",
    poster: "https://upload.wikimedia.org/wikipedia/en/3/3a/Aquaman_poster.jpg",
    genre: "Action, Adventure, Fantasy",
    rating: "6.8",
    overview: "Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land.",
    cast: "Jason Momoa, Amber Heard, Willem Dafoe, Patrick Wilson, Nicole Kidman",
    trailerId: "WDkg3h8PCVU",
    downloadUrl: "#"
  },
  joker1: {
    title: "Joker",
    year: "2019",
    poster: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg",
    genre: "Crime, Drama, Thriller",
    rating: "8.4",
    overview: "A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.",
    cast: "Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy",
    trailerId: "zAGVQLHvwOY",
    downloadUrl: "#"
  },
  thebatman: {
    title: "The Batman",
    year: "2022",
    poster: "https://upload.wikimedia.org/wikipedia/en/f/ff/The_Batman_%28film%29_poster.jpg",
    genre: "Action, Crime, Drama",
    rating: "7.8",
    overview: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.",
    cast: "Robert Pattinson, Zoë Kravitz, Jeffrey Wright, Colin Farrell, Paul Dano",
    trailerId: "mqqft2x_Aa4",
    downloadUrl: "#"
  }
};
  
